apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.15/manifests/ha/install.yaml
  - ingress.yaml
  - repository.yaml
  - projects.yaml
  - application-set.yaml

images:
  - name: quay.io/argoproj/argocd:v2.6.15
    # Se desejar usar sua própria imagem, ajuste newName e newTag.
    # newName: ghcr.io/jeffersonvalente/argocd
    # newTag: latest

patchesStrategicMerge:
  - argocd-rbac-cm.patch.yaml
  - argocd-cm.patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --insecure
  # Remove as regras de affinity do Deployment do argocd-server
  - target:
      kind: Deployment
      name: argocd-server
    patch: |
      - op: replace
        path: /spec/template/spec/affinity
        value: {}
  # Remove as regras de affinity do Deployment do argocd-redis-ha-haproxy (se existir)
  - target:
      kind: Deployment
      name: argocd-redis-ha-haproxy
    patch: |
      - op: replace
        path: /spec/template/spec/affinity
        value: {}
  # Remove as regras de affinity do Deployment do argocd-repo-server (se existir)
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |
      - op: replace
        path: /spec/template/spec/affinity
        value: {}
  # Remove as regras de affinity do StatefulSet do argocd-redis-ha-server (se existir)
  - target:
      kind: StatefulSet
      name: argocd-redis-ha-server
    patch: |
      - op: replace
        path: /spec/template/spec/affinity
        value: {}