apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: SEUREPO
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
            SUA CHAVE PRIVADA
    -----END OPENSSH PRIVATE KEY-----