apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <<SEU REPOSITORIO>>
  sshPrivateKey: |
            <SUA CHAVE PRIVADA>
